const fs = require('fs-extra');
const path = require('path');

const books = [
    { title: "Chip War", author: "Chris Miller", priority: 9.8, genre: "Economics / Geo-Pol" },
    { title: "Neuromancer", author: "William Gibson", priority: 9.8, genre: "Cyberpunk / Tech" },
    { title: "Designing Data-Intensive Applications", author: "Martin Kleppmann", priority: 9.7, genre: "Tech / Architecture" },
    { title: "Capital Vol. 1", author: "Karl Marx", priority: 9.5, genre: "Political Economy" },
    { title: "Meditations", author: "Marcus Aurelius", priority: 9.5, genre: "Philosophy / Stoic" },
    { title: "Crafting Interpreters", author: "Robert Nystrom", priority: 9.5, genre: "Tech / Dev" },
    { title: "Dune", author: "Frank Herbert", priority: 9.4, genre: "Sci-Fi / Strategy" },
    { title: "Snow Crash", author: "Neal Stephenson", priority: 9.4, genre: "Cyberpunk / Tech" },
    { title: "Maus I & II", author: "Art Spiegelman", priority: 9.3, genre: "Graphic Novel / History" },
    { title: "Maus: A Survivor's Tale", author: "Art Spiegelman", priority: 9.3, genre: "Graphic Novel" },
    { title: "The Shellcoder's Handbook", author: "Felix Lindner", priority: 9.3, genre: "Cybersecurity" },
    { title: "1984", author: "George Orwell", priority: 9.3, genre: "Classic / Dystopian" },
    { title: "Hacking: The Art of Exploitation", author: "Jon Erickson", priority: 9.3, genre: "Cybersecurity" },
    { title: "Cryptonomicon", author: "Neal Stephenson", priority: 9.2, genre: "Cyberpunk / History" },
    { title: "Ghost in the Wires", author: "Kevin Mitnick", priority: 9.1, genre: "Cybersecurity / Bio" },
    { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", priority: 9.1, genre: "Cyberpunk / Sci-Fi" },
    { title: "The Difference Engine", author: "William Gibson & Bruce Sterling", priority: 9.1, genre: "Steampunk / Sci-Fi" },
    { title: "Sandworm", author: "Andy Greenberg", priority: 9, genre: "Cybersecurity / War" },
    { title: "Seeing Like a State", author: "James C. Scott", priority: 9, genre: "Political Theory" },
    { title: "Ficciones", author: "Jorge Luis Borges", priority: 9, genre: "Literature / Surreal" },
    { title: "Countdown to Zero Day (Stuxnet)", author: "Kim Zetter", priority: 9, genre: "Cybersecurity / History" },
    { title: "Discipline and Punish", author: "Michel Foucault", priority: 8.9, genre: "Philosophy / Power" },
    { title: "Imperialism: The Highest Stage of Capitalism", author: "Vladimir Lenin", priority: 8.9, genre: "Political Economy" },
    { title: "Schismatrix Plus", author: "Bruce Sterling", priority: 8.8, genre: "Cyberpunk / Transhuman" },
    { title: "Breaking and Entering", author: "Jeremy N. Smith", priority: 8.8, genre: "Cybersecurity / Bio" },
    { title: "The Master and Margarita", author: "Mikhail Bulgakov", priority: 8.8, genre: "Literature / Surreal" },
    { title: "Blindsight", author: "Peter Watts", priority: 8.8, genre: "Sci-Fi / Hard" },
    { title: "Exhalation", author: "Ted Chiang", priority: 8.8, genre: "Sci-Fi / Philosophy" },
    { title: "The Dispossessed", author: "Ursula K. Le Guin", priority: 8.8, genre: "Sci-Fi / Political" },
    { title: "Animal Farm", author: "George Orwell", priority: 8.7, genre: "Classic / Political" },
    { title: "Computer Systems: A Programmer's Perspective", author: "Randal Bryant", priority: 8.7, genre: "Tech / Architecture" },
    { title: "Fahrenheit 451", author: "Ray Bradbury", priority: 8.7, genre: "Classic / Dystopian" },
    { title: "Algorithm Design Manual", author: "Steven Skiena", priority: 8.7, genre: "Tech / CS" },
    { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", priority: 8.7, genre: "Sci-Fi / Political" },
    { title: "The Puzzle Palace", author: "James Bamford", priority: 8.6, genre: "Intel / Espionage" },
    { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", priority: 8.6, genre: "Classic / Sci-Fi" },
    { title: "The Handmaid's Tale", author: "Margaret Atwood", priority: 8.6, genre: "Classic / Dystopian" },
    { title: "Winnie-the-Pooh", author: "A.A. Milne", priority: 8.5, genre: "Aesthetic / Cottage" },
    { title: "Hyperion", author: "Dan Simmons", priority: 8.5, genre: "Sci-Fi / Literary" },
    { title: "Introduction to Linear Algebra", author: "Gilbert Strang", priority: 8.5, genre: "Math / CS" },
    { title: "The Wind in the Willows", author: "Kenneth Grahame", priority: 8.5, genre: "Aesthetic / Cottage" },
    { title: "Cat's Cradle", author: "Kurt Vonnegut", priority: 8.5, genre: "Classic / Sci-Fi" },
    { title: "Parable of the Sower", author: "Octavia E. Butler", priority: 8.5, genre: "Sci-Fi / Dystopian" },
    { title: "Piranesi", author: "Susanna Clarke", priority: 8.5, genre: "Aesthetic / Fantasy" },
    { title: "Johnny Mnemonic", author: "William Gibson", priority: 8.5, genre: "Cyberpunk / Short" },
    { title: "Sapiens", author: "Yuval Noah Harari", priority: 8.5, genre: "History / Macro" },
    { title: "Structure and Interpretation of Computer Programs", author: "Abelson & Sussman", priority: 8.4, genre: "Tech / CS" },
    { title: "Brave New World", author: "Aldous Huxley", priority: 8.4, genre: "Classic / Dystopian" },
    { title: "The Art of Intrusion", author: "Kevin Mitnick", priority: 8.4, genre: "Cybersecurity" },
    { title: "Quantum Mechanics: The Theoretical Minimum", author: "Leonard Susskind", priority: 8.4, genre: "Science / Physics" },
    { title: "The Tale of Genji", author: "Murasaki Shikibu", priority: 8.4, genre: "Classic / Eastern" },
    { title: "Myth of Sisyphus", author: "Albert Camus", priority: 8.3, genre: "Philosophy" },
    { title: "Social Engineering: The Art of Human Hacking", author: "Christopher Hadnagy", priority: 8.3, genre: "Cybersecurity / Social" },
    { title: "Scale", author: "Geoffrey West", priority: 8.3, genre: "Science / Systems" },
    { title: "The Lord of the Rings", author: "J.R.R. Tolkien", priority: 8.3, genre: "Fantasy / Epic" },
    { title: "The Hobbit", author: "J.R.R. Tolkien", priority: 8.3, genre: "Fantasy / Epic" },
    { title: "The Prince", author: "Niccolò Machiavelli", priority: 8.3, genre: "Strategy / Politics" },
    { title: "A Wizard of Earthsea", author: "Ursula K. Le Guin", priority: 8.3, genre: "Fantasy / Classic" },
    { title: "The Lion the Witch and the Wardrobe", author: "C.S. Lewis", priority: 8.2, genre: "Fantasy / Classic" },
    { title: "Kiki's Delivery Service", author: "Eiko Kadono", priority: 8.2, genre: "Fantasy / Ghibli" },
    { title: "Beyond Good and Evil", author: "Friedrich Nietzsche", priority: 8.2, genre: "Philosophy" },
    { title: "How Do You Live?", author: "Genzaburo Yoshino", priority: 8.2, genre: "Classic / Eastern" },
    { title: "Nausicaä of the Valley of the Wind (Manga)", author: "Hayao Miyazaki", priority: 8.2, genre: "Manga / Ghibli" },
    { title: "When Marnie Was There", author: "Joan G. Robinson", priority: 8.2, genre: "Fantasy / Ghibli" },
    { title: "The Republic", author: "Plato", priority: 8.2, genre: "Philosophy" },
    { title: "Count Zero", author: "William Gibson", priority: 8.2, genre: "Cyberpunk / Tech" },
    { title: "War by Other Means", author: "Jennifer Harris", priority: 8.1, genre: "Geopolitics" },
    { title: "The Art of Deception", author: "Kevin Mitnick", priority: 8.1, genre: "Cybersecurity / Social" },
    { title: "Antifragile", author: "Nassim Taleb", priority: 8.1, genre: "Philosophy / Econ" },
    { title: "Mona Lisa Overdrive", author: "William Gibson", priority: 8.1, genre: "Cyberpunk / Tech" },
    { title: "Burning Chrome", author: "William Gibson", priority: 8.1, genre: "Cyberpunk / Short" },
    { title: "Complete Sherlock Holmes", author: "Arthur Conan Doyle", priority: 8, genre: "Mystery / Aesthetic" },
    { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", priority: 8, genre: "Classic / Lit" },
    { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", priority: 8, genre: "Classic / Aesthetic" },
    { title: "Communist Manifesto", author: "Marx & Engels", priority: 8, genre: "Political Economy" },
    { title: "Roadside Picnic", author: "Strugatsky Brothers", priority: 8, genre: "Sci-Fi / Soviet" },
    { title: "Stealing the Network: How to Own the Box", author: "Syngress", priority: 8, genre: "Cybersecurity / Fic" },
    { title: "Crime and Punishment", author: "Fyodor Dostoevsky", priority: 7.9, genre: "Classic / Lit" },
    { title: "Manufacturing Consent", author: "Noam Chomsky", priority: 7.9, genre: "Political / Media" },
    { title: "Advanced Lock Picking Secrets", author: "Steven Hampton", priority: 7.9, genre: "Tradecraft / Lock" },
    { title: "A Study in Scarlet", author: "Arthur Conan Doyle", priority: 7.8, genre: "Mystery / Aesthetic" },
    { title: "The Sign of Four", author: "Arthur Conan Doyle", priority: 7.8, genre: "Mystery / Aesthetic" },
    { title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", priority: 7.8, genre: "Mystery / Aesthetic" },
    { title: "The Secret Garden", author: "Frances H. Burnett", priority: 7.8, genre: "Classic / Aesthetic" },
    { title: "The Wretched of the Earth", author: "Frantz Fanon", priority: 7.8, genre: "Political / Rev" },
    { title: "Condition of Working Class in England", author: "Friedrich Engels", priority: 7.8, genre: "Political Economy" },
    { title: "Origins of Totalitarianism", author: "Hannah Arendt", priority: 7.8, genre: "Political Theory" },
    { title: "Settlers", author: "J. Sakai", priority: 7.8, genre: "Political / History" },
    { title: "Little Women", author: "Louisa May Alcott", priority: 7.8, genre: "Classic / Aesthetic" },
    { title: "On Practice and Contradiction", author: "Mao Zedong", priority: 7.8, genre: "Philosophy / Strategy" },
    { title: "Oryx and Crake", author: "Margaret Atwood", priority: 7.8, genre: "Sci-Fi / Dystopian" },
    { title: "Persepolis", author: "Marjane Satrapi", priority: 7.8, genre: "Graphic Novel / Bio" },
    { title: "A Court of Silver Flames", author: "Sarah J. Maas", priority: 7.8, genre: "Classics / History" },
    { title: "Leviathan", author: "Thomas Hobbes", priority: 7.8, genre: "Political Theory" },
    { title: "The Stranger", author: "Albert Camus", priority: 7.7, genre: "Classic / Lit" },
    { title: "Tress of the Emerald Sea", author: "Brandon Sanderson", priority: 7.7, genre: "Fantasy / Aesthetic" },
    { title: "The Tin Drum", author: "Günter Grass", priority: 7.7, genre: "Classic / Lit" },
    { title: "Moby-Dick", author: "Herman Melville", priority: 7.7, genre: "Classic / Lit" },
    { title: "Heidi", author: "Johanna Spyri", priority: 7.7, genre: "Classic / Aesthetic" },
    { title: "Matilda", author: "Roald Dahl", priority: 7.7, genre: "Classic / Children" },
    { title: "The BFG", author: "Roald Dahl", priority: 7.7, genre: "Classic / Children" },
    { title: "Jane Eyre", author: "Charlotte Brontë", priority: 7.6, genre: "Classic / Lit" },
    { title: "Metamorphosis", author: "Franz Kafka", priority: 7.6, genre: "Classic / Surreal" },
    { title: "Middlemarch", author: "George Eliot", priority: 7.6, genre: "Classic / Lit" },
    { title: "Pride and Prejudice", author: "Jane Austen", priority: 7.6, genre: "Classic / Lit" },
    { title: "The Grapes of Wrath", author: "John Steinbeck", priority: 7.6, genre: "Classic / Lit" },
    { title: "Of Mice and Men", author: "John Steinbeck", priority: 7.6, genre: "Classic / Lit" },
    { title: "Romance of the Three Kingdoms", author: "Luo Guanzhong", priority: 7.6, genre: "Classic / Eastern" },
    { title: "Six Easy Pieces", author: "Richard Feynman", priority: 7.6, genre: "Science / Physics" },
    { title: "V for Vendetta", author: "Alan Moore", priority: 7.5, genre: "Graphic Novel" },
    { title: "Pippi Longstocking", author: "Astrid Lindgren", priority: 7.5, genre: "Classic / Children" },
    { title: "A Short History of Nearly Everything", author: "Bill Bryson", priority: 7.5, genre: "Science / General" },
    { title: "A Christmas Carol", author: "Charles Dickens", priority: 7.5, genre: "Classic / Lit" },
    { title: "The Three-Body Problem", author: "Cixin Liu", priority: 7.5, genre: "Sci-Fi / Hard" },
    { title: "Dark Forest", author: "Cixin Liu", priority: 7.5, genre: "Sci-Fi / Hard" },
    { title: "Death's End", author: "Cixin Liu", priority: 7.5, genre: "Sci-Fi / Hard" },
    { title: "Bury My Heart at Wounded Knee", author: "Dee Brown", priority: 7.5, genre: "History / Indigenous" },
    { title: "Wuthering Heights", author: "Emily Brontë", priority: 7.5, genre: "Classic / Lit" },
    { title: "The Trial", author: "Franz Kafka", priority: 7.5, genre: "Classic / Surreal" },
    { title: "Notes from Underground", author: "Fyodor Dostoevsky", priority: 7.5, genre: "Classic / Lit" },
    { title: "The Idiot", author: "Fyodor Dostoevsky", priority: 7.5, genre: "Classic / Lit" },
    { title: "Demons", author: "Fyodor Dostoevsky", priority: 7.5, genre: "Classic / Lit" },
    { title: "Sense and Sensibility", author: "Jane Austen", priority: 7.5, genre: "Classic / Lit" },
    { title: "Stealing the Network: Own an Identity", author: "Jay Beale", priority: 7.5, genre: "Cybersecurity / Fic" },
    { title: "Stealing the Network: Own a Continent", author: "Joe Grand", priority: 7.5, genre: "Cybersecurity / Fic" },
    { title: "Charlie and the Chocolate Factory", author: "Roald Dahl", priority: 7.5, genre: "Classic / Children" },
    { title: "James and the Giant Peach", author: "Roald Dahl", priority: 7.5, genre: "Classic / Children" },
    { title: "The Witches", author: "Roald Dahl", priority: 7.5, genre: "Classic / Children" },
    { title: "A Court of Wings and Ruin", author: "Sarah J. Maas", priority: 7.5, genre: "Fantasy / Romance" },
    { title: "A Court of Mist and Fury", author: "Sarah J. Maas", priority: 7.5, genre: "Fantasy / Romance" },
    { title: "A Court of Thorns and Roses", author: "Sarah J. Maas", priority: 7.5, genre: "Fantasy / Romance" },
    { title: "Solaris", author: "Stanislaw Lem", priority: 7.5, genre: "Sci-Fi / Soviet" },
    { title: "The Princess Bride", author: "William Goldman", priority: 7.5, genre: "Fantasy / Classic" },
    { title: "Great Expectations", author: "Charles Dickens", priority: 7.4, genre: "Classic / Lit" },
    { title: "A Tale of Two Cities", author: "Charles Dickens", priority: 7.4, genre: "Classic / Lit" },
    { title: "Tao Te Ching", author: "Lao Tzu", priority: 7.4, genre: "Philosophy / Eastern" },
    { title: "Frankenstein", author: "Mary Shelley", priority: 7.4, genre: "Classic / Gothic" },
    { title: "House of Sky and Breath", author: "Sarah J. Maas", priority: 7.4, genre: "Fantasy / Romance" },
    { title: "House of Flame and Shadow", author: "Sarah J. Maas", priority: 7.4, genre: "Fantasy / Romance" },
    { title: "We", author: "Yevgeny Zamyatin", priority: 7.4, genre: "Sci-Fi / Dystopian" },
    { title: "The Count of Monte Cristo", author: "Alexandre Dumas", priority: 7.3, genre: "Classic / Adventure" },
    { title: "Dracula", author: "Bram Stoker", priority: 7.3, genre: "Classic / Gothic" },
    { title: "Peter Pan", author: "J.M. Barrie", priority: 7.3, genre: "Classic / Children" },
    { title: "Blindness", author: "José Saramago", priority: 7.3, genre: "Literature / Surreal" },
    { title: "Picture of Dorian Gray", author: "Oscar Wilde", priority: 7.3, genre: "Classic / Gothic" },
    { title: "The Man Without Qualities", author: "Robert Musil", priority: 7.3, genre: "Classic / Lit" },
    { title: "A Clockwork Orange", author: "Anthony Burgess", priority: 7.2, genre: "Classic / Dystopian" },
    { title: "A Season in Hell", author: "Arthur Rimbaud", priority: 7.2, genre: "Poetry" },
    { title: "Paris Spleen", author: "Charles Baudelaire", priority: 7.2, genre: "Poetry" },
    { title: "The Flowers of Evil", author: "Charles Baudelaire", priority: 7.2, genre: "Poetry" },
    { title: "Metro 2033", author: "Dmitry Glukhovsky", priority: 7.2, genre: "Sci-Fi / Post-Apoc" },
    { title: "Old Man and the Sea", author: "Ernest Hemingway", priority: 7.2, genre: "Classic / Lit" },
    { title: "The Great Gatsby", author: "F. Scott Fitzgerald", priority: 7.2, genre: "Classic / Lit" },
    { title: "To Kill a Mockingbird", author: "Harper Lee", priority: 7.2, genre: "Classic / Lit" },
    { title: "Siddhartha", author: "Hermann Hesse", priority: 7.2, genre: "Classic / Lit" },
    { title: "Catcher in the Rye", author: "J.D. Salinger", priority: 7.2, genre: "Classic / Lit" },
    { title: "Simulacra and Simulation", author: "Jean Baudrillard", priority: 7.2, genre: "Philosophy" },
    { title: "East of Eden", author: "John Steinbeck", priority: 7.2, genre: "Classic / Lit" },
    { title: "Swann in Love", author: "Marcel Proust", priority: 7.2, genre: "Classic / Lit" },
    { title: "Swann's Way", author: "Marcel Proust", priority: 7.2, genre: "Classic / Lit" },
    { title: "Dream of the Red Chamber", author: "Tsao Hsueh-Chin", priority: 7.2, genre: "Classic / Eastern" },
    { title: "Lord of the Flies", author: "William Golding", priority: 7.2, genre: "Classic / Lit" },
    { title: "Things Fall Apart", author: "Chinua Achebe", priority: 7.1, genre: "Classic / Lit" },
    { title: "The Sun Also Rises", author: "Ernest Hemingway", priority: 7.1, genre: "Classic / Lit" },
    { title: "A Farewell to Arms", author: "Ernest Hemingway", priority: 7.1, genre: "Classic / Lit" },
    { title: "Romancero Gitano", author: "Federico García Lorca", priority: 7.1, genre: "Fantasy" },
    { title: "The Book of Disquiet", author: "Fernando Pessoa", priority: 7.1, genre: "Literature / Surreal" },
    { title: "Steppenwolf", author: "Hermann Hesse", priority: 7.1, genre: "Classic / Lit" },
    { title: "Catch-22", author: "Joseph Heller", priority: 7.1, genre: "Classic / Lit" },
    { title: "Pedro Páramo", author: "Juan Rulfo", priority: 7.1, genre: "Literature / Surreal" },
    { title: "Miraculous Stories from... Tradition", author: "Kyoko Motomuchi Nakamura", priority: 7.1, genre: "Fantasy" },
    { title: "A Scanner Darkly", author: "Philip K. Dick", priority: 7.1, genre: "Cyberpunk / Sci-Fi" },
    { title: "Beloved", author: "Toni Morrison", priority: 7.1, genre: "Classic / Lit" },
    { title: "State and Revolution", author: "Vladimir Lenin", priority: 7.1, genre: "Political Theory" },
    { title: "The Fall", author: "Albert Camus", priority: 7, genre: "Philosophy / Lit" },
    { title: "Logic / Organon", author: "Aristotle", priority: 7, genre: "Philosophy" },
    { title: "The Intelligent Investor", author: "Benjamin Graham", priority: 7, genre: "Finance" },
    { title: "Structural Anthropology", author: "Claude Lévi-Strauss", priority: 7, genre: "Anthropology" },
    { title: "Rebecca", author: "Daphne du Maurier", priority: 7, genre: "Classic / Mystery" },
    { title: "The Raven", author: "Edgar Allan Poe", priority: 7, genre: "Poetry" },
    { title: "All Quiet on the Western Front", author: "Erich Maria Remarque", priority: 7, genre: "Classic / War" },
    { title: "The Gift of Fear", author: "Gavin de Becker", priority: 7, genre: "Psychology / Safety" },
    { title: "Counterintelligence: Theory and Practice", author: "Jan Goldman", priority: 7, genre: "Intel / Espionage" },
    { title: "Persuasion", author: "Jane Austen", priority: 7, genre: "Classic / Lit" },
    { title: "Guns Germs and Steel", author: "Jared Diamond", priority: 7, genre: "History / Macro" },
    { title: "The Art of Deception", author: "Kevin Mitnick", priority: 7, genre: "Cybersecurity / Social" },
    { title: "The Complete Essays", author: "Michel de Montaigne", priority: 7, genre: "Philosophy" },
    { title: "How to Read a Book", author: "Mortimer Adler", priority: 7, genre: "Self-Edu" },
    { title: "Ender's Game", author: "Orson Scott Card", priority: 7, genre: "Sci-Fi / Strategy" },
    { title: "The Valis Trilogy", author: "Philip K. Dick", priority: 7, genre: "Sci-Fi / Surreal" },
    { title: "Trial and Death of Socrates", author: "Plato", priority: 7, genre: "Philosophy" },
    { title: "Watership Down", author: "Richard Adams", priority: 7, genre: "Classic / Adventure" },
    { title: "Treasure Island", author: "Robert Louis Stevenson", priority: 7, genre: "Classic / Adventure" },
    { title: "The Jungle Book", author: "Rudyard Kipling", priority: 7, genre: "Classic / Children" },
    { title: "A Court of Frost and Starlight", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / Romance" },
    { title: "The Assassin and the Empire", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "The Assassin and the Underworld", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "The Assassin and the Princess", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "The Assassin and the Pirate Lord", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "The Assassin and the Healer", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "The Assassin and the Desert", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Throne of Glass", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Crown of Midnight", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Heir of Fire", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Queen of Shadows", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Empire of Storms", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Tower of Dawn", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "Kingdom of Ash", author: "Sarah J. Maas", priority: 7, genre: "Fantasy / YA" },
    { title: "ACOSF - Azriel Bonus Chapter", author: "Sarah J. Maas", priority: 7, genre: "Poetry" },
    { title: "The Captain and the Prince", author: "Sarah J. Maas", priority: 7, genre: "Mythology / Folk" },
    { title: "True Names", author: "Vernor Vinge", priority: 7, genre: "Cyberpunk / Sci-Fi" },
    { title: "What Is to Be Done?", author: "Vladimir Lenin", priority: 7, genre: "Political Theory" },
    { title: "Lolita", author: "Vladimir Nabokov", priority: 7, genre: "Classic / Lit" },
    { title: "Julius Caesar", author: "William Shakespeare", priority: 7, genre: "Classic / Play" },
    { title: "War and Peace", author: "Leo Tolstoy", priority: 6.9, genre: "Classic / Lit" },
    { title: "Math for Computer Science", author: "Meyer/Leighton", priority: 6.9, genre: "Math / CS" },
    { title: "Readings in Database Systems", author: "Michael Stonebraker", priority: 6.9, genre: "Tech / DB" },
    { title: "Midnight's Children", author: "Salman Rushdie", priority: 6.9, genre: "Classic / Lit" },
    { title: "Les Misérables", author: "Victor Hugo", priority: 6.9, genre: "Classic / Lit" },
    { title: "Grimm's Fairy Tales", author: "Brothers Grimm", priority: 6.8, genre: "Classic / Folklore" },
    { title: "Liars & Outliers", author: "Bruce Schneier", priority: 6.8, genre: "Cybersecurity / Trust" },
    { title: "God Is Not Great", author: "Christopher Hitchens", priority: 6.8, genre: "Religion / Critical" },
    { title: "Thinking Fast and Slow", author: "Daniel Kahneman", priority: 6.8, genre: "Psychology" },
    { title: "The Maltese Falcon", author: "Dashiell Hammett", priority: 6.8, genre: "Mystery / Noir" },
    { title: "Love in the Time of Cholera", author: "Gabriel García Márquez", priority: 6.8, genre: "Classic / Lit" },
    { title: "Hans Christian Andersen's Fairy Tales", author: "H.C. Andersen", priority: 6.8, genre: "Classic / Folklore" },
    { title: "Complete Fairy Tales", author: "Hans Christian Andersen", priority: 6.8, genre: "Classic / Folklore" },
    { title: "Portrait of the Artist as a Young Man", author: "James Joyce", priority: 6.8, genre: "Classic / Lit" },
    { title: "Anna Karenina", author: "Leo Tolstoy", priority: 6.8, genre: "Classic / Lit" },
    { title: "The Big Sleep", author: "Raymond Chandler", priority: 6.8, genre: "Mystery / Noir" },
    { title: "The Long Goodbye", author: "Raymond Chandler", priority: 6.8, genre: "Mystery / Noir" },
    { title: "Leaves of Grass", author: "Walt Whitman", priority: 6.8, genre: "Poetry" },
    { title: "And Then There Were None", author: "Agatha Christie", priority: 6.7, genre: "Mystery" },
    { title: "Murder on the Orient Express", author: "Agatha Christie", priority: 6.7, genre: "Mystery" },
    { title: "Howl and Other Poems", author: "Allen Ginsberg", priority: 6.7, genre: "Poetry" },
    { title: "Fight Club", author: "Chuck Palahniuk", priority: 6.7, genre: "Fiction" },
    { title: "Dubliners", author: "James Joyce", priority: 6.7, genre: "Classic / Lit" },
    { title: "Heart of a Dog", author: "Mikhail Bulgakov", priority: 6.7, genre: "Literature / Satire" },
    { title: "Priory of the Orange Tree", author: "Samantha Shannon", priority: 6.7, genre: "Fantasy" },
    { title: "Waiting for Godot", author: "Samuel Beckett", priority: 6.7, genre: "Classic / Play" },
    { title: "The Waste Land", author: "T.S. Eliot", priority: 6.7, genre: "Poetry" },
    { title: "Mrs. Dalloway", author: "Virginia Woolf", priority: 6.7, genre: "Classic / Lit" },
    { title: "To the Lighthouse", author: "Virginia Woolf", priority: 6.7, genre: "Classic / Lit" },
    { title: "Mockingbird", author: "Walter Tevis", priority: 6.7, genre: "Sci-Fi / Dystopian" },
    { title: "The Sound and the Fury", author: "William Faulkner", priority: 6.7, genre: "Classic / Lit" },
    { title: "As I Lay Dying", author: "William Faulkner", priority: 6.7, genre: "Classic / Lit" },
    { title: "Absalom Absalom!", author: "William Faulkner", priority: 6.7, genre: "Classic / Lit" },
    { title: "Midsummer Night's Dream", author: "William Shakespeare", priority: 6.7, genre: "Classic / Play" },
    { title: "Howl's Moving Castle", author: "Diana Wynne Jones", priority: 6.6, genre: "Fantasy / Ghibli" },
    { title: "Capital Vol 2 & 3", author: "Karl Marx", priority: 6.6, genre: "Political Economy" },
    { title: "Njal's Saga", author: "Unknown", priority: 6.6, genre: "Classic / Saga" },
    { title: "Grave of the Fireflies", author: "Akiyuki Nosaka", priority: 6.5, genre: "Fiction / War" },
    { title: "The Doors of Perception", author: "Aldous Huxley", priority: 6.5, genre: "Philosophy / Psych" },
    { title: "Berlin Alexanderplatz", author: "Alfred Döblin", priority: 6.5, genre: "Classic / Lit" },
    { title: "The Arabian Nights", author: "Anonymous", priority: 6.5, genre: "Classic / Folklore" },
    { title: "Mahabharata", author: "Anonymous", priority: 6.5, genre: "Classic / Eastern" },
    { title: "The Book of Job", author: "Anonymous", priority: 6.5, genre: "Religion" },
    { title: "Uncle Vanya", author: "Anton Chekhov", priority: 6.5, genre: "Classic / Play" },
    { title: "Selected Stories of Anton Chekhov", author: "Anton Chekhov", priority: 6.5, genre: "Classic / Lit" },
    { title: "Uncle Vanya", author: "Anton Chekhov", priority: 6.5, genre: "Classic / Play" },
    { title: "Whisper of the Heart", author: "Aoi Hiiragi", priority: 6.5, genre: "Manga / Ghibli" },
    { title: "The Cat Returns", author: "Aoi Hiiragi", priority: 6.5, genre: "Manga / Ghibli" },
    { title: "Aristotle I", author: "Aristotle", priority: 6.5, genre: "Philosophy" },
    { title: "Operating Systems (OSTEP)", author: "Arpaci-Dusseau", priority: 6.5, genre: "Tech / CS" },
    { title: "His Last Bow", author: "Arthur Conan Doyle", priority: 6.5, genre: "General Fiction" },
    { title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", priority: 6.5, genre: "General Fiction" },
    { title: "The Memoirs of Sherlock Holmes", author: "Arthur Conan Doyle", priority: 6.5, genre: "General Fiction" },
    { title: "The Return of Sherlock Holmes", author: "Arthur Conan Doyle", priority: 6.5, genre: "General Fiction" },
    { title: "The Valley of Fear", author: "Arthur Conan Doyle", priority: 6.5, genre: "General Fiction" },
    { title: "The Crucible", author: "Arthur Miller", priority: 6.5, genre: "Classic / Play" },
    { title: "Swallows and Amazons", author: "Arthur Ransome", priority: 6.5, genre: "Classic / Children" },
    { title: "Ethics", author: "Baruch Spinoza", priority: 6.5, genre: "Philosophy" },
    { title: "The Conquest of Happiness", author: "Bertrand Russell", priority: 6.5, genre: "Philosophy" },
    { title: "A Walk in the Woods", author: "Bill Bryson", priority: 6.5, genre: "Travel / Memoir" },
    { title: "At Home", author: "Bill Bryson", priority: 6.5, genre: "History / General" },
    { title: "The Body", author: "Bill Bryson", priority: 6.5, genre: "Science / General" },
    { title: "Pensées", author: "Blaise Pascal", priority: 6.5, genre: "Philosophy / Rel" },
    { title: "Islands in the Net", author: "Bruce Sterling", priority: 6.5, genre: "Cyberpunk / Lit" },
    { title: "The Dragons of Eden", author: "Carl Sagan", priority: 6.5, genre: "Science / General" },
    { title: "1491", author: "Charles C. Mann", priority: 6.5, genre: "History / Pre-Col" },
    { title: "The Origin of Species", author: "Charles Darwin", priority: 6.5, genre: "Science / Bio" },
    { title: "Oliver Twist", author: "Charles Dickens", priority: 6.5, genre: "Classic / Lit" },
    { title: "The Cuckoo's Egg", author: "Clifford Stoll", priority: 6.5, genre: "Cybersecurity / Hist" },
    { title: "Thinking", author: "Daniel Kahneman", priority: 6.5, genre: "Psychology" },
    { title: "A More Perfect Heaven", author: "Dava Sobel", priority: 6.5, genre: "Science / Hist" },
    { title: "Anti-Oedipus", author: "Deleuze & Guattari", priority: 6.5, genre: "Philosophy" },
    { title: "A Thousand Plateaus", author: "Deleuze & Guattari", priority: 6.5, genre: "Philosophy" },
    { title: "Jacques the Fatalist", author: "Denis Diderot", priority: 6.5, genre: "Classic / Lit" },
    { title: "Earwig and the Witch", author: "Diana Wynne Jones", priority: 6.5, genre: "Fantasy / Children" },
    { title: "The Golden Notebook", author: "Doris Lessing", priority: 6.5, genre: "Classic / Lit" },
    { title: "From the Mixed-Up Files of Mrs. Basil E.", author: "E.L. Konigsburg", priority: 6.5, genre: "Classic / Children" },
    { title: "The Fool's Progress", author: "Edward Abbey", priority: 6.5, genre: "Fiction / Nature" },
    { title: "The Little White Horse", author: "Elizabeth Goudge", priority: 6.5, genre: "Classic / Children" },
    { title: "Medea", author: "Euripides", priority: 6.5, genre: "Classic / Play" },
    { title: "The Castle", author: "Franz Kafka", priority: 6.5, genre: "Classic / Surreal" },
    { title: "The Concept of Mind", author: "Gilbert Ryle", priority: 6.5, genre: "Philosophy" },
    { title: "Island of Dr. Moreau", author: "H.G. Wells", priority: 6.5, genre: "Classic / Sci-Fi" },
    { title: "The Time Machine", author: "H.G. Wells", priority: 6.5, genre: "Classic / Sci-Fi" },
    { title: "Spirited Away Film Comic", author: "Hayao Miyazaki", priority: 6.5, genre: "Manga / Ghibli" },
    { title: "A Doll's House", author: "Henrik Ibsen", priority: 6.5, genre: "Classic / Play" },
    { title: "Manufacturing Consent", author: "Herman & Chomsky", priority: 6.5, genre: "Political / Media" },
    { title: "Herodotus | Thucydides", author: "Herodotus/Thucydides", priority: 6.5, genre: "History / Classic" },
    { title: "Pere Goriot", author: "Honoré de Balzac", priority: 6.5, genre: "Classic / Lit" },
    { title: "A People's History of the United States", author: "Howard Zinn", priority: 6.5, genre: "History / Alt" },
    { title: "Zeno's Conscience", author: "Italo Svevo", priority: 6.5, genre: "Classic / Lit" },
    { title: "Carmilla", author: "J. Sheridan Le Fanu", priority: 6.5, genre: "Classic / Gothic" },
    { title: "On the Road", author: "Jack Kerouac", priority: 6.5, genre: "Classic / Beat" },
    { title: "The Dharma Bums", author: "Jack Kerouac", priority: 6.5, genre: "Classic / Beat" },
    { title: "The Call of the Wild", author: "Jack London", priority: 6.5, genre: "Classic / Adventure" },
    { title: "Kushiel's Dart", author: "Jacqueline Carey", priority: 6.5, genre: "Fantasy" },
    { title: "The Postman Always Rings Twice", author: "James M. Cain", priority: 6.5, genre: "Mystery / Noir" },
    { title: "Double Indemnity", author: "James M. Cain", priority: 6.5, genre: "Mystery / Noir" },
    { title: "Discourse on Inequality", author: "Jean-Jacques Rousseau", priority: 6.5, genre: "Philosophy" },
    { title: "A Century of Spies", author: "Jeffrey T. Richelson", priority: 6.5, genre: "History / Intel" },
    { title: "The Scholars", author: "Jingzi Wu", priority: 6.5, genre: "Classic / Eastern" },
    { title: "Grande Sertão: Veredas", author: "João Guimarães Rosa", priority: 6.5, genre: "Classic / Lit" },
    { title: "Goethe's Faust", author: "Johann Wolfgang von Goethe", priority: 6.5, genre: "Classic / Play" },
    { title: "The Pearl", author: "John Steinbeck", priority: 6.5, genre: "Classic / Lit" },
    { title: "Nostromo", author: "Joseph Conrad", priority: 6.5, genre: "Classic / Lit" },
    { title: "Twenty Thousand Leagues Under the Sea", author: "Jules Verne", priority: 6.5, genre: "Classic / Sci-Fi" },
    { title: "The German Ideology", author: "Karl Marx", priority: 6.5, genre: "Political Philosophy" },
    { title: "Dispatches for the NY Tribune", author: "Karl Marx", priority: 6.5, genre: "Political / History" },
    { title: "The 18th Brumaire of Louis Bonaparte", author: "Karl Marx", priority: 6.5, genre: "Political / History" },
    { title: "The Civil War in France", author: "Karl Marx", priority: 6.5, genre: "Political / History" },
    { title: "The Economic and Philosophic Manuscripts", author: "Karl Marx", priority: 6.5, genre: "Philosophy / Econ" },
    { title: "A Thousand Splendid Suns", author: "Khaled Hosseini", priority: 6.5, genre: "Fiction / Modern" },
    { title: "A Coney Island of the Mind", author: "Lawrence Ferlinghetti", priority: 6.5, genre: "Poetry" },
    { title: "A Universe from Nothing", author: "Lawrence M. Krauss", priority: 6.5, genre: "Science / Physics" },
    { title: "Ivan the Fool", author: "Leo Tolstoy", priority: 6.5, genre: "Classic / Fable" },
    { title: "Diary of a Madman", author: "Lu Xun", priority: 6.5, genre: "Classic / Eastern" },
    { title: "Six Characters in Search of an Author", author: "Luigi Pirandello", priority: 6.5, genre: "Classic / Play" },
    { title: "The Dream Machine", author: "M. Mitchell Waldrop", priority: 6.5, genre: "Tech / History" },
    { title: "Autobiography of Malcolm X", author: "Malcolm X", priority: 6.5, genre: "Bio / Political" },
    { title: "Memoirs of Hadrian", author: "Marguerite Yourcenar", priority: 6.5, genre: "Classic / Lit" },
    { title: "The Adventures of Huckleberry Finn", author: "Mark Twain", priority: 6.5, genre: "Classic / Lit" },
    { title: "The Adventures of Tom Sawyer", author: "Mark Twain", priority: 6.5, genre: "Classic / Lit" },
    { title: "Lakota Woman", author: "Mary Crow Dog", priority: 6.5, genre: "Bio / Indigenous" },
    { title: "The Borrowers", author: "Mary Norton", priority: 6.5, genre: "Classic / Children" },
    { title: "Where the Wild Things Are", author: "Maurice Sendak", priority: 6.5, genre: "Classic / Children" },
    { title: "I Know Why the Caged Bird Sings", author: "Maya Angelou", priority: 6.5, genre: "Memoir" },
    { title: "Che Guevara and the FBI", author: "Michael Ratner", priority: 6.5, genre: "History / Intel" },
    { title: "The Unbearable Lightness of Being", author: "Milan Kundera", priority: 6.5, genre: "Classic / Lit" },
    { title: "Children of the Alley", author: "Naguib Mahfouz", priority: 6.5, genre: "Classic / Lit" },
    { title: "On the Revolutions of Heavenly Spheres", author: "Nicolaus Copernicus", priority: 6.5, genre: "Science / Hist" },
    { title: "Metamorphoses", author: "Ovid", priority: 6.5, genre: "Classic / Myth" },
    { title: "Perfume: The Story of a Murderer", author: "Patrick Süskind", priority: 6.5, genre: "Fiction / Historical" },
    { title: "Poems of Paul Celan", author: "Paul Celan", priority: 6.5, genre: "Poetry" },
    { title: "Harmony", author: "Project Itoh", priority: 6.5, genre: "Sci-Fi / Anime" },
    { title: "Strange Stories From A Chinese Studio", author: "Pu Songling", priority: 6.5, genre: "Classic / Eastern" },
    { title: "Principles of Philosophy", author: "René Descartes", priority: 6.5, genre: "Philosophy" },
    { title: "Fantastic Mr. Fox", author: "Roald Dahl", priority: 6.5, genre: "Classic / Children" },
    { title: "The Strange Case of Dr. Jekyll and Mr. Hyde", author: "Robert Louis Stevenson", priority: 6.5, genre: "Classic / Gothic" },
    { title: "2666", author: "Roberto Bolaño", priority: 6.5, genre: "Literature / Modern" },
    { title: "Distant Star", author: "Roberto Bolaño", priority: 6.5, genre: "Literature / Modern" },
    { title: "Masnavi-Ma'navi", author: "Rumi", priority: 6.5, genre: "Poetry / Spirit" },
    { title: "The Satanic Verses", author: "Salman Rushdie", priority: 6.5, genre: "Fiction / Modern" },
    { title: "Molloy / Malone Dies / Unnamable", author: "Samuel Beckett", priority: 6.5, genre: "Classic / Lit" },
    { title: "Oedipus Rex", author: "Sophocles", priority: 6.5, genre: "Classic / Play" },
    { title: "The Red and the Black", author: "Stendhal", priority: 6.5, genre: "Classic / Lit" },
    { title: "Ariel", author: "Sylvia Plath", priority: 6.5, genre: "Poetry" },
    { title: "The War for Reality", author: "T.C. Weber", priority: 6.5, genre: "Sci-Fi / Modern" },
    { title: "Zero-Day Rising", author: "T.C. Weber", priority: 6.5, genre: "Sci-Fi / Modern" },
    { title: "Sleep State Interrupt", author: "T.C. Weber", priority: 6.5, genre: "Sci-Fi / Modern" },
    { title: "The Council", author: "T.C. Weber", priority: 6.5, genre: "Sci-Fi / Modern" },
    { title: "Born in Salt", author: "T.C. Weber", priority: 6.5, genre: "Sci-Fi / Modern" },
    { title: "The Story", author: "T.C. Weber", priority: 6.5, genre: "Sci-Fi / Modern" },
    { title: "Death in Venice", author: "Thomas Mann", priority: 6.5, genre: "Classic / Lit" },
    { title: "Gravity's Rainbow", author: "Thomas Pynchon", priority: 6.5, genre: "Literature / Complex" },
    { title: "The Theory of the Leisure Class", author: "Thorstein Veblen", priority: 6.5, genre: "Sociology / Econ" },
    { title: "On Tyranny", author: "Timothy Snyder", priority: 6.5, genre: "Political / History" },
    { title: "In Cold Blood", author: "Truman Capote", priority: 6.5, genre: "True Crime / Lit" },
    { title: "My Neighbor Totoro", author: "Tsugiko Kubo", priority: 6.5, genre: "Fantasy / Ghibli" },
    { title: "The Epic of Gilgamesh", author: "Unknown", priority: 6.5, genre: "Classic / Epic" },
    { title: "Ramayana", author: "Valmiki", priority: 6.5, genre: "Classic / Eastern" },
    { title: "Aeschylus | Sophocles | Euripides", author: "Various", priority: 6.5, genre: "Classic / Play" },
    { title: "Testament of Youth", author: "Vera Brittain", priority: 6.5, genre: "Memoir / War" },
    { title: "Left-Wing Communism", author: "Vladimir Lenin", priority: 6.5, genre: "Political Theory" },
    { title: "First Love", author: "Vladimir Nabokov", priority: 6.5, genre: "Classic / Lit" },
    { title: "Candide", author: "Voltaire", priority: 6.5, genre: "Classic / Satire" },
    { title: "The Rings of Saturn", author: "W.G. Sebald", priority: 6.5, genre: "Literature / Travel" },
    { title: "Romeo and Juliet", author: "William Shakespeare", priority: 6.5, genre: "Classic / Play" },
    { title: "The Tempest", author: "William Shakespeare", priority: 6.5, genre: "Classic / Play" },
    { title: "Twelfth Night", author: "William Shakespeare", priority: 6.5, genre: "Classic / Play" },
    { title: "King Lear", author: "William Shakespeare", priority: 6.5, genre: "Classic / Play" },
    { title: "Nexus: A Brief History", author: "Yuval Noah Harari", priority: 6.5, genre: "History / Macro" },
    { title: "Tropic of Cancer", author: "Henry Miller", priority: 6.4, genre: "Classic / Lit" },
    { title: "Nausea", author: "Jean-Paul Sartre", priority: 6.4, genre: "Philosophy / Fic" },
    { title: "Hunger", author: "Knut Hamsun", priority: 6.4, genre: "Classic / Lit" },
    { title: "Jin Ping Mei", author: "Lanling Xiaoxiao Sheng", priority: 6.4, genre: "Classic / Eastern" },
    { title: "Journey to the End of the Night", author: "Louis-Ferdinand Céline", priority: 6.4, genre: "Classic / Lit" },
    { title: "From Max Weber: Essays in Sociology", author: "Max Weber", priority: 6.4, genre: "Sociology" },
    { title: "Economy and Society", author: "Max Weber", priority: 6.4, genre: "Sociology" },
    { title: "The Water Margin", author: "Shi Nai'an", priority: 6.4, genre: "Classic / Eastern" },
    { title: "Civilization and Its Discontents", author: "Sigmund Freud", priority: 6.4, genre: "Psychology" },
    { title: "Naked Lunch", author: "William S. Burroughs", priority: 6.4, genre: "Classic / Beat" },
    { title: "The Devil's Dictionary", author: "Ambrose Bierce", priority: 6.3, genre: "Satire" },
    { title: "Death of a Salesman", author: "Arthur Miller", priority: 6.3, genre: "Classic / Play" },
    { title: "Collected Tales of Edgar Allan Poe", author: "Edgar Allan Poe", priority: 6.3, genre: "Classic / Gothic" },
    { title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey", priority: 6.3, genre: "Classic / Lit" },
    { title: "The Sound of the Mountain", author: "Yasunari Kawabata", priority: 6.3, genre: "Classic / Eastern" },
    { title: "Wealth of Nations", author: "Adam Smith", priority: 6.2, genre: "Economics" },
    { title: "Doctor Zhivago", author: "Boris Pasternak", priority: 6.2, genre: "Classic / Historical" },
    { title: "Debt: The First 5000 Years", author: "David Graeber", priority: 6.2, genre: "Anthropology / Econ" },
    { title: "Bullshit Jobs", author: "David Graeber", priority: 6.2, genre: "Anthropology / Econ" },
    { title: "Society of the Spectacle", author: "Guy Debord", priority: 6.2, genre: "Philosophy" },
    { title: "Bartleby the Scrivener", author: "Herman Melville", priority: 6.2, genre: "Classic / Lit" },
    { title: "Fear and Loathing in Las Vegas", author: "Hunter S. Thompson", priority: 6.2, genre: "New Journalism" },
    { title: "Hell's Angels", author: "Hunter S. Thompson", priority: 6.2, genre: "New Journalism" },
    { title: "Gone with the Wind", author: "Margaret Mitchell", priority: 6.2, genre: "Classic / Historical" },
    { title: "Yellowface", author: "R.F. Kuang", priority: 6.2, genre: "Fiction / Modern" },
    { title: "Invisible Man", author: "Ralph Ellison", priority: 6.2, genre: "Classic / Lit" },
    { title: "Native Son", author: "Richard Wright", priority: 6.2, genre: "Classic / Lit" },
    { title: "Season of Migration to the North", author: "Tayeb Salih", priority: 6.2, genre: "Classic / Lit" },
    { title: "A Streetcar Named Desire", author: "Tennessee Williams", priority: 6.2, genre: "Classic / Play" },
    { title: "The Glass Menagerie", author: "Tennessee Williams", priority: 6.2, genre: "Classic / Play" },
    { title: "Electric Kool-Aid Acid Test", author: "Tom Wolfe", priority: 6.2, genre: "New Journalism" },
    { title: "Breakfast at Tiffany's", author: "Truman Capote", priority: 6.2, genre: "Classic / Lit" },
    { title: "The Golden Bough", author: "James George Frazer", priority: 6.1, genre: "Anthropology / Myth" },
    { title: "Hero with a Thousand Faces", author: "Joseph Campbell", priority: 6.1, genre: "Mythology" },
    { title: "Heart of Darkness", author: "Joseph Conrad", priority: 6.1, genre: "Classic / Lit" },
    { title: "Book of Five Rings", author: "Miyamoto Musashi", priority: 6.1, genre: "Strategy" },
    { title: "Dead Souls", author: "Nikolai Gogol", priority: 6.1, genre: "Classic / Lit" },
    { title: "Interpretation of Dreams", author: "Sigmund Freud", priority: 6.1, genre: "Psychology" },
    { title: "Art of War", author: "Sun Tzu", priority: 6.1, genre: "Strategy" },
    { title: "Rebuilding Milo", author: "Aaron Horschig", priority: 6, genre: "Health / Physio" },
    { title: "Syntopicon of Great Books (Vol II)", author: "Adler", priority: 6, genre: "Reference" },
    { title: "The Grapes of Math", author: "Alex Bellos", priority: 6, genre: "Math / Pop" },
    { title: "Alex's Adventures in Numberland", author: "Alex Bellos", priority: 6, genre: "Math / Pop" },
    { title: "Philippine Society and Revolution", author: "Amado Guerrero", priority: 6, genre: "Political / History" },
    { title: "The Holy Bible: KJV", author: "Anonymous", priority: 6, genre: "Religion" },
    { title: "Baron: The Cat Returns", author: "Aoi Hiiragi", priority: 6, genre: "Manga / Ghibli" },
    { title: "Aristotle II", author: "Aristotle", priority: 6, genre: "Philosophy" },
    { title: "The Lady who Loved Insects", author: "Arthur Waley", priority: 6, genre: "Classic / Eastern" },
    { title: "The Six Bullerby Children", author: "Astrid Lindgren", priority: 6, genre: "Classic / Children" },
    { title: "Maoists in India", author: "Azad", priority: 6, genre: "Political / History" },
    { title: "American Psycho", author: "Bret Easton Ellis", priority: 6, genre: "Fiction / Satire" },
    { title: "The Nature of Life", author: "C.H. Waddington", priority: 6, genre: "Science / Bio" },
    { title: "The Copernicus Complex", author: "Caleb Scharf", priority: 6, genre: "Science / Astro" },
    { title: "The Otterbury Incident", author: "Cecil Day-Lewis", priority: 6, genre: "Classic / Children" },
    { title: "A People's History of the World", author: "Chris Harman", priority: 6, genre: "History / Marxist" },
    { title: "Colossus and the Crab", author: "D.F. Jones", priority: 6, genre: "Sci-Fi / Classic" },
    { title: "The Fall of Colossus", author: "D.F. Jones", priority: 6, genre: "Sci-Fi / Classic" },
    { title: "Colossus", author: "D.F. Jones", priority: 6, genre: "Sci-Fi / Classic" },
    { title: "The Prussian Officer", author: "D.H. Lawrence", priority: 6, genre: "Short Story" },
    { title: "Sons and Lovers", author: "D.H. Lawrence", priority: 6, genre: "Classic / Lit" },
    { title: "Ishmael", author: "Daniel Quinn", priority: 6, genre: "Philosophy / Fic" },
    { title: "Green Eggs and Ham", author: "Dr. Seuss", priority: 6, genre: "Classic / Children" },
    { title: "The Little Bookroom", author: "Eleanor Farjeon", priority: 6, genre: "Classic / Children" },
    { title: "History", author: "Elsa Morante", priority: 6, genre: "Classic / Lit" },
    { title: "The Flying Classroom", author: "Erich Kästner", priority: 6, genre: "Classic / Children" },
    { title: "Ecotopia", author: "Ernest Callenbach", priority: 6, genre: "Sci-Fi / Utopian" },
    { title: "Long Day's Journey Into Night", author: "Eugene O'Neill", priority: 6, genre: "Classic / Play" },
    { title: "Mourning Becomes Electra", author: "Eugene O'Neill", priority: 6, genre: "Classic / Play" },
    { title: "Little Lord Fauntleroy", author: "Frances Hodgson Burnett", priority: 6, genre: "Classic / Children" },
    { title: "Saint Joan", author: "George Bernard Shaw", priority: 6, genre: "Classic / Play" },
    { title: "A Void", author: "Georges Perec", priority: 6, genre: "Literature / Oulipo" },
    { title: "Adventures of Cipollino", author: "Gianni Rodari", priority: 6, genre: "Classic / Children" },
    { title: "The Teenage Liberation Handbook", author: "Grace Llewellyn", priority: 6, genre: "Self-Edu" },
    { title: "Principia Discordia", author: "Gregory Hill", priority: 6, genre: "Counterculture" },
    { title: "Die Nibelungen Sage", author: "Gustav Schalk", priority: 6, genre: "Classic / Myth" },
    { title: "Inside CIA's Private World", author: "H. Bradford Westerfield", priority: 6, genre: "Intel / History" },
    { title: "Basic History of Art", author: "H.W. Janson", priority: 6, genre: "Art / History" },
    { title: "The Beast In The Jungle", author: "Henry James", priority: 6, genre: "Classic / Lit" },
    { title: "Hippocrates | Galen", author: "Hippocrates/Galen", priority: 6, genre: "Science / Hist" },
    { title: "The Stolen Heir", author: "Holly Black", priority: 6, genre: "Fantasy / YA" },
    { title: "The Prisoner's Throne", author: "Holly Black", priority: 6, genre: "Fantasy / YA" },
    { title: "The Voyages of Doctor Dolittle", author: "Hugh Lofting", priority: 6, genre: "Classic / Children" },
    { title: "Trainspotting", author: "Irvine Welsh", priority: 6, genre: "Fiction / Satire" },
    { title: "Revolution Sabotaged Before it Began", author: "Iwakami Yasumi", priority: 6, genre: "Political / History" },
    { title: "Freedom from the Known", author: "J. Krishnamurti", priority: 6, genre: "Philosophy / Spirit" },
    { title: "In a Glass Darkly", author: "J. Sheridan Le Fanu", priority: 6, genre: "Classic / Gothic" },
    { title: "Surface Tension", author: "James Blish", priority: 6, genre: "Sci-Fi / Classic" },
    { title: "Secrets of a Buccaneer-Scholar", author: "James Marcus Bach", priority: 6, genre: "Self-Edu" },
    { title: "Lies My Teacher Told Me", author: "James W. Loewen", priority: 6, genre: "History / Ed" },
    { title: "Souvenirs entomologiques", author: "Jean-Henri Fabre", priority: 6, genre: "Science / Nature" },
    { title: "The Principles of Morals and Legislation", author: "Jeremy Bentham", priority: 6, genre: "Philosophy" },
    { title: "The Autumn of the Middle Ages", author: "Johan Huizinga", priority: 6, genre: "History / Medieval" },
    { title: "War by Other Means", author: "John J. Fialka", priority: 6, genre: "Espionage / Econ" },
    { title: "General Theory of Employment", author: "John Maynard Keynes", priority: 6, genre: "Economics" },
    { title: "Toward a Philosophy of History", author: "José Ortega y Gasset", priority: 6, genre: "Philosophy / Hist" },
    { title: "Powers of Horror", author: "Julia Kristeva", priority: 6, genre: "Philosophy" },
    { title: "The Recognition of Sakuntala", author: "Kalidasa", priority: 6, genre: "Classic / Eastern" },
    { title: "Untouchable God", author: "Kancha Ilaiah", priority: 6, genre: "Political / Social" },
    { title: "Nine Fairy Tales", author: "Karel Čapek", priority: 6, genre: "Classic / Children" },
    { title: "Poverty of Philosophy", author: "Karl Marx", priority: 6, genre: "Political Economy" },
    { title: "The Restaurant of Many Orders", author: "Kenji Miyazawa", priority: 6, genre: "Classic / Eastern" },
    { title: "Korean Children's Favorite Stories", author: "Kim So-Un", priority: 6, genre: "Classic / Children" },
    { title: "Miraculous Stories from Japan", author: "Kyoko Motomuchi Nakamura", priority: 6, genre: "Classic / Eastern" },
    { title: "Heaven on Earth", author: "L.S. Fauber", priority: 6, genre: "Science / Hist" },
    { title: "Quotations from Chairman Mao", author: "Mao Zedong", priority: 6, genre: "Political Theory" },
    { title: "Hans Brinker", author: "Mary Mapes Dodge", priority: 6, genre: "Classic / Children" },
    { title: "Tistou les pouces verts", author: "Maurice Druon", priority: 6, genre: "Classic / Children" },
    { title: "Lethal Interface", author: "Mel Odom", priority: 6, genre: "Cyberpunk / Lit" },
    { title: "Oathbreakers", author: "Mercedes Lackey", priority: 6, genre: "Fantasy" },
    { title: "Violence: A New Approach", author: "Michel Wieviorka", priority: 6, genre: "Sociology" },
    { title: "Don Quixote", author: "Miguel de Cervantes", priority: 6, genre: "Classic / Lit" },
    { title: "Puzzlecraft", author: "Mike Selinker", priority: 6, genre: "Hobby / Game" },
    { title: "Anatomy of a Short Story", author: "Nabokov", priority: 6, genre: "Lit Crit" },
    { title: "Shock Doctrine", author: "Naomi Klein", priority: 6, genre: "Political / Econ" },
    { title: "The Book Nobody Read", author: "Owen Gingerich", priority: 6, genre: "Science / Hist" },
    { title: "The Little Humpbacked Horse", author: "Pyotr Yershov", priority: 6, genre: "Classic / Folklore" },
    { title: "The Acquisitive Society", author: "R.H. Tawney", priority: 6, genre: "Political Economy" },
    { title: "Marxism and Literature", author: "Raymond Williams", priority: 6, genre: "Lit Crit" },
    { title: "Operating Systems: Three Easy Pieces", author: "Remzi Arpaci-Dusseau", priority: 6, genre: "Tech / CS" },
    { title: "The Most Dangerous Game", author: "Richard Connell", priority: 6, genre: "Short Story" },
    { title: "Sick Societies", author: "Robert Edgerton", priority: 6, genre: "Sociology" },
    { title: "The Great Conversation", author: "Robert Maynard Hutchins", priority: 6, genre: "Philosophy / Ed" },
    { title: "Life Boat Mutiny", author: "Robert Sheckley", priority: 6, genre: "Sci-Fi / Classic" },
    { title: "The Eagle of the Ninth", author: "Rosemary Sutcliff", priority: 6, genre: "Classic / YA" },
    { title: "The Orchard (Bostan)", author: "Saadi", priority: 6, genre: "Poetry / Eastern" },
    { title: "I Am That", author: "Sri Nisargadatta Maharaj", priority: 6, genre: "Philosophy / Spirit" },
    { title: "All the World's a Simulation", author: "Stephen Moles", priority: 6, genre: "Sci-Fi / Philosophy" },
    { title: "The Wrath of Leviathan", author: "T.C. Weber", priority: 6, genre: "Sci-Fi / Modern" },
    { title: "The Central Philosophy of Buddhism", author: "T.R.V. Murti", priority: 6, genre: "Philosophy / Rel" },
    { title: "Kokurikozaka Kara", author: "Tetsuro Sayama", priority: 6, genre: "Manga / Ghibli" },
    { title: "Utopia", author: "Thomas More", priority: 6, genre: "Philosophy / Pol" },
    { title: "Common Sense", author: "Thomas Paine", priority: 6, genre: "History / Pol" },
    { title: "Capital in the 21st Century", author: "Thomas Piketty", priority: 6, genre: "Economics" },
    { title: "Flashbacks", author: "Timothy Leary", priority: 6, genre: "Memoir / Counter" },
    { title: "A Nursery Tale", author: "Vladimir Nabokov", priority: 6, genre: "Classic / Lit" },
    { title: "Anatomy of a Short Story", author: "Vladimir Nabokov", priority: 6, genre: "Lit Crit" },
    { title: "A Lost Lady", author: "Willa Cather", priority: 6, genre: "Classic / Lit" },
    { title: "Titus Andronicus", author: "William Shakespeare", priority: 6, genre: "Classic / Play" },
    { title: "Journey to the West (Vol 1-4)", author: "Wu Ch'eng-En", priority: 6, genre: "Classic / Eastern" },
    { title: "Confessions", author: "St. Augustine", priority: 5.9, genre: "Philosophy / Rel" },
    { title: "Homo Deus", author: "Yuval Noah Harari", priority: 5.9, genre: "History / Future" },
    { title: "Canterbury Tales", author: "Geoffrey Chaucer", priority: 5.8, genre: "Classic / Lit" },
    { title: "The Cruel Prince", author: "Holly Black", priority: 5.8, genre: "Fantasy / YA" },
    { title: "The Wicked King", author: "Holly Black", priority: 5.8, genre: "Fantasy / YA" },
    { title: "The Queen of Nothing", author: "Holly Black", priority: 5.8, genre: "Fantasy / YA" },
    { title: "The Iliad & The Odyssey", author: "Homer", priority: 5.8, genre: "Classic / Epic" },
    { title: "Faust", author: "Johann Wolfgang von Goethe", priority: 5.8, genre: "Classic / Play" },
    { title: "Paradise Lost", author: "John Milton", priority: 5.8, genre: "Classic / Epic" },
    { title: "The Selfish Gene", author: "Richard Dawkins", priority: 5.8, genre: "Science / Bio" },
    { title: "A Day of Fallen Night", author: "Samantha Shannon", priority: 5.8, genre: "Fantasy" },
    { title: "Among the Burning Flowers", author: "Samantha Shannon", priority: 5.8, genre: "Fantasy" },
    { title: "Beowulf", author: "Unknown", priority: 5.8, genre: "Classic / Epic" },
    { title: "The Aeneid", author: "Virgil", priority: 5.8, genre: "Classic / Epic" },
    { title: "Minimanual of the Urban Guerrilla", author: "Carlos Marighella", priority: 5.7, genre: "Political Theory" },
    { title: "How to Win Friends & Influence People", author: "Dale Carnegie", priority: 5.7, genre: "Self-Help" },
    { title: "The Road to Serfdom", author: "Friedrich Hayek", priority: 5.7, genre: "Economics / Pol" },
    { title: "Foundations of Leninism", author: "Joseph Stalin", priority: 5.7, genre: "Political Theory" },
    { title: "Hamlet", author: "William Shakespeare", priority: 5.7, genre: "Classic / Play" },
    { title: "Macbeth", author: "William Shakespeare", priority: 5.7, genre: "Classic / Play" },
    { title: "King Lear", author: "William Shakespeare", priority: 5.7, genre: "Classic / Play" },
    { title: "Othello", author: "William Shakespeare", priority: 5.7, genre: "Classic / Play" },
    { title: "The Divine Comedy", author: "Dante Alighieri", priority: 5.6, genre: "Classic / Epic" },
    { title: "Anna Karenina", author: "Leo Tolstoy", priority: 5.6, genre: "Classic / Lit" },
    { title: "Bombs Beards and Barricades", author: "Anthony Esler", priority: 5.5, genre: "History / Social" },
    { title: "The Albino Album", author: "Chavisa Woods", priority: 5.5, genre: "Fiction / Modern" },
    { title: "Marxism Leninism Maoism Study Notes", author: "CPI (Maoist)", priority: 5.5, genre: "Political Theory" },
    { title: "Complete Guide to Lock Picking", author: "Eddie the Wire", priority: 5.5, genre: "Tradecraft" },
    { title: "The Radium Woman", author: "Eleanor Doorly", priority: 5.5, genre: "Bio / Science" },
    { title: "Gargantua and Pantagruel", author: "François Rabelais", priority: 5.5, genre: "Classic / Lit" },
    { title: "Decameron", author: "Giovanni Boccaccio", priority: 5.5, genre: "Classic / Lit" },
    { title: "Madame Bovary", author: "Gustave Flaubert", priority: 5.5, genre: "Classic / Lit" },
    { title: "Sentimental Education", author: "Gustave Flaubert", priority: 5.5, genre: "Classic / Lit" },
    { title: "The Ship That Flew", author: "Hilda Lewis", priority: 5.5, genre: "Classic / Children" },
    { title: "Works of Hippocrates", author: "Hippocrates", priority: 5.5, genre: "Science / History" },
    { title: "Hacking the Human", author: "Ian Mann", priority: 5.5, genre: "Cybersecurity / Social" },
    { title: "Tristram Shandy", author: "Laurence Sterne", priority: 5.5, genre: "Classic / Lit" },
    { title: "Zen and the Art of Motorcycle Maintenance", author: "Robert Pirsig", priority: 5.5, genre: "Philosophy / Fic" },
    { title: "The Month-Brothers", author: "Samuel Marshak", priority: 5.5, genre: "Classic / Children" },
    { title: "Robinson Crusoe", author: "Daniel Defoe", priority: 5.4, genre: "Classic / Adventure" },
    { title: "Tom Jones", author: "Henry Fielding", priority: 5.4, genre: "Classic / Lit" },
    { title: "Gulliver's Travels", author: "Jonathan Swift", priority: 5.4, genre: "Classic / Satire" },
    { title: "Ivanhoe", author: "Walter Scott", priority: 5.3, genre: "Classic / Historical" },
    { title: "Last of the Mohicans", author: "James Fenimore Cooper", priority: 5.2, genre: "Classic / Historical" },
    { title: "Uncle Tom's Cabin", author: "Harriet Beecher Stowe", priority: 5.1, genre: "Classic / Historical" },
    { title: "Checkered Fences", author: "Alma Hudson", priority: 5, genre: "Fiction / General" },
    { title: "Charnel House", author: "Andrew James Pritchard", priority: 5, genre: "Fiction / Horror" },
    { title: "Circle In the Sand", author: "Andrew James Pritchard", priority: 5, genre: "Fiction / General" },
    { title: "The Red Tent", author: "Anita Diamant", priority: 5, genre: "Fiction / Historical" },
    { title: "The Little Prince", author: "Antoine de Saint-Exupéry", priority: 5, genre: "Classic / Children" },
    { title: "Dogs of Orninica", author: "Daniel Unedo", priority: 5, genre: "Fiction / General" },
    { title: "RoboChildren", author: "James Hunt", priority: 5, genre: "Sci-Fi / Indie" },
    { title: "Christina - Kartanon varjoissa", author: "K.M. Peyton", priority: 5, genre: "Fiction / General" },
    { title: "Bylo nas pet", author: "Karel Polacek", priority: 5, genre: "Fiction / General" },
    { title: "The Free", author: "M. Gilliland", priority: 5, genre: "Fiction / General" },
    { title: "A Norwegian Family", author: "Marie Hamsun", priority: 5, genre: "Fiction / General" },
    { title: "Justine", author: "Marquis de Sade", priority: 5, genre: "Classic / Erotica" },
    { title: "Les Princes du vent", author: "Michel-Aimé Baudouy", priority: 5, genre: "Fiction / General" },
    { title: "The Scarlet Letter", author: "Nathaniel Hawthorne", priority: 5, genre: "Classic / Lit" },
    { title: "What the Neighbors Did", author: "Philippa Pearce", priority: 5, genre: "Fiction / General" }
];

const basePath = path.join(__dirname, 'src', 'content', 'books');


// Helper to slugify
function slugify(text) {
    return text.toLowerCase()
        .replace(/[^\w\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-');
}

async function main() {
    await fs.emptyDir(basePath);
    await fs.outputFile(path.join(basePath, 'index.md'), '---\ntitle: Books\ndescription: My Library\ntags: [books]\n---\n\n<!-- H1 handled by template -->\n\nBooks arranged by genre.');

    for (const book of books) {
        // Parse Genres: Take the first one as primary folder
        const genres = book.genre.split('/').map(g => g.trim());
        const primaryGenre = slugify(genres[0]);
        const bookSlug = slugify(book.title);

        const genreDir = path.join(basePath, primaryGenre);
        await fs.ensureDir(genreDir);

        // Create Genre Index if missing
        const genreIndex = path.join(genreDir, 'index.md');
        if (!await fs.pathExists(genreIndex)) {
            const title = genres[0];
            await fs.outputFile(genreIndex, `---
title: ${title}
description: Books in ${title}
tags: [${primaryGenre}]
---

<!-- H1 handled by template -->
`);
        }

        const filePath = path.join(genreDir, `${bookSlug}.md`);
        const content = `---
title: "${book.title}"
author: "${book.author}"
priority: ${book.priority}
tags: [${genres.map(g => `"${g}"`).join(', ')}]
description: "Overview of ${book.title} by ${book.author}."
---

<!-- H1 removed to avoid duplication with Template H1 -->

*   **Author**: ${book.author}
*   **Genre**: ${book.genre}

## Overview

*(Detailed overview coming soon...)*
`;
        await fs.outputFile(filePath, content);
    }
    console.log(`Generated ${books.length} book files.`);
}

main().catch(console.error);
